# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
language: "ruby"
sudo: false
script: "bundle exec rake --trace"
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby
  - rbx-2
notifications:
  irc: "irc.freenode.org#savon"

matrix:
  allow_failures:
    - rvm: jruby-head
